version: '3.7'

networks:
  app-tier:
    driver: bridge
services:
  mysql:
    networks:
      - app-tier
    platform: linux/x86_64
    container_name: reserve_db
    restart: always
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - '3308:3306'
  redis: # Example Service
    networks:
      - app-tier
    platform: linux/x86_64
    container_name: reserve_redis
    restart: always
    image: redis
    expose:
      - '6379'
